stages:
  - test1
  - build1

test1:
  stage: test1
  image: golang:1.17
  tags:
    - netology-1
  script:
    - go test ./...

build1:
  stage: build1
  image: docker:latest
  tags:
    - netology-1
  script:
    - docker build -t my-app .
