stages:
  - test1
  - build1

test1:
  stage: test1
  image: golang:1.17
  tags:
    - netology-1
  script:
    - go test .

build1:
  stage: build1
  image: docker:latest
  tags:
    - netology-1
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker build -t my-app .
